# Generated by Django 5.0.1 on 2024-01-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='name',
            new_name='model',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(default='1', verbose_name='Внешний ИД'),
        ),
    ]
