# Generated by Django 5.0.1 on 2024-01-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
