# Generated by Django 5.0.1 on 2024-01-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_productinfo_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Внешний ИД'),
        ),
    ]
