# Generated by Django 5.0.1 on 2024-01-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_productinfo_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, verbose_name='Внешний ИД'),
        ),
    ]
