# Generated by Django 5.0.1 on 2024-01-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_productinfo_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparametr',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Стоимость'),
        ),
    ]
