# Generated by Django 5.0.1 on 2024-02-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='state',
        ),
    ]
