# Generated by Django 5.0.1 on 2024-02-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_status_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contact', verbose_name='Контакт'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
