# Generated by Django 5.0.1 on 2024-02-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_contact_options_remove_contact_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_sum',
        ),
    ]
